<#
.SYNOPSIS
  Downloads the pinned BASS packages listed in tools/native-deps.json into native/bass/ (E0-S3).

  Layout produced (all gitignored):
    native/bass/include/<name>.h        headers (only mpcore/src/audio may include them; a Catch2 test enforces it)
    native/bass/lib/x64/<name>.lib      import libraries
    native/bass/bin/x64/<name>.dll      runtime DLLs, packaged with the app
    native/bass/licenses/<name>.txt     licence / readme text of each package (shown by the About page)
    native/bass/.cache/<name>.zip       verified downloads
    native/bass/manifest.lock.txt       what was fetched: name, version line, sha256

  Every zip is verified against the SHA-256 in the manifest before anything is extracted; a mismatch is a
  hard failure (exit 1) so an upstream re-release never enters the build unnoticed.
.PARAMETER ManifestPath
  Alternative manifest (default: tools/native-deps.json).
.PARAMETER PrintHashes
  Maintenance: download every package without verifying and print the current SHA-256 values.
.PARAMETER Force
  Ignore the cache and download everything again.
#>
[CmdletBinding()]
param(
    [string]$ManifestPath,
    [switch]$PrintHashes,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
Add-Type -AssemblyName System.IO.Compression.FileSystem

$toolsDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $toolsDir
if (-not $ManifestPath) { $ManifestPath = Join-Path $toolsDir 'native-deps.json' }
$manifest = Get-Content -Raw -LiteralPath $ManifestPath | ConvertFrom-Json

$root = Join-Path $repoRoot ($manifest.root -replace '/', '\')
$dirs = @{
    include  = Join-Path $root 'include'
    lib      = Join-Path $root 'lib\x64'
    bin      = Join-Path $root 'bin\x64'
    licenses = Join-Path $root 'licenses'
    cache    = Join-Path $root '.cache'
}
foreach ($d in $dirs.Values) { New-Item -ItemType Directory -Force -Path $d | Out-Null }

function Get-Sha256([string]$Path) {
    (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()
}

function Get-Package($pkg) {
    $zip = Join-Path $dirs.cache "$($pkg.name).zip"
    if (-not $Force -and (Test-Path -LiteralPath $zip) -and (Get-Sha256 $zip) -eq $pkg.sha256) {
        Write-Host "  cached   $($pkg.name)"
        return $zip
    }
    $tmp = "$zip.download"
    Write-Host "  download $($pkg.url)"
    Invoke-WebRequest -Uri $pkg.url -OutFile $tmp -UseBasicParsing
    $actual = Get-Sha256 $tmp
    if ($PrintHashes) {
        Write-Host ("  {0,-12} {1}" -f $pkg.name, $actual)
        Move-Item -Force -LiteralPath $tmp -Destination $zip
        return $zip
    }
    if ($actual -ne $pkg.sha256) {
        Remove-Item -Force -LiteralPath $tmp
        throw "SHA-256 mismatch for $($pkg.name) from $($pkg.url)`n  expected $($pkg.sha256)`n  actual   $actual`nun4seen may have re-released the package; review the change, then update tools/native-deps.json (tools/fetch-native.ps1 -PrintHashes)."
    }
    Move-Item -Force -LiteralPath $tmp -Destination $zip
    return $zip
}

function Extract-Entry([IO.Compression.ZipArchive]$archive, [string]$entryName, [string]$destination) {
    $entry = $archive.Entries | Where-Object { $_.FullName -eq $entryName } | Select-Object -First 1
    if (-not $entry) { throw "entry '$entryName' not found in archive (layout changed upstream?)" }
    [IO.Compression.ZipFileExtensions]::ExtractToFile($entry, $destination, $true)
}

Write-Host "Fetching native packages from $ManifestPath into $root"
$lock = New-Object System.Collections.Generic.List[string]
$lock.Add("# Generated by tools/fetch-native.ps1 on $(Get-Date -Format s). Do not edit.")
foreach ($pkg in $manifest.packages) {
    $zip = Get-Package $pkg
    if ($PrintHashes) { continue }

    $archive = [IO.Compression.ZipFile]::OpenRead($zip)
    try {
        Extract-Entry $archive $pkg.header  (Join-Path $dirs.include  (Split-Path -Leaf $pkg.header))
        Extract-Entry $archive $pkg.lib     (Join-Path $dirs.lib      (Split-Path -Leaf $pkg.lib))
        Extract-Entry $archive $pkg.dll     (Join-Path $dirs.bin      (Split-Path -Leaf $pkg.dll))
        $licencePath = Join-Path $dirs.licenses "$($pkg.name).txt"
        Extract-Entry $archive $pkg.licence $licencePath
        $versionLine = (Get-Content -LiteralPath $licencePath -TotalCount 1).Trim()
        $lock.Add(("{0,-12} {1,-28} {2}" -f $pkg.name, $versionLine, $pkg.sha256))
        Write-Host ("  ok       {0,-12} {1}" -f $pkg.name, $versionLine)
    }
    finally { $archive.Dispose() }
}

if (-not $PrintHashes) {
    Set-Content -LiteralPath (Join-Path $root 'manifest.lock.txt') -Value $lock -Encoding UTF8
    Write-Host "Done: $($manifest.packages.Count) packages in $root"
}
exit 0
